<?php
$TinyMCE->addLang('danish','da');
$TinyMCE->addLang('english','en');
$TinyMCE->addLang('english-british','en');
$TinyMCE->addLang('finnish','fi');
$TinyMCE->addLang('francais','fr');
$TinyMCE->addLang('francais-utf8','fr');
$TinyMCE->addLang('german','de');
$TinyMCE->addLang('italian','it');
$TinyMCE->addLang('japanese-utf8','ja_utf-8');
$TinyMCE->addLang('nederlands','nl');
$TinyMCE->addLang('norsk','nn');
$TinyMCE->addLang('persian','fa');
$TinyMCE->addLang('polish','pl');
$TinyMCE->addLang('portuguese','pt');
$TinyMCE->addLang('russian','ru');
$TinyMCE->addLang('russion-UTF8','ru');
$TinyMCE->addLang('simple_chinese-gb2312','zh_cn');
$TinyMCE->addLang('spanish','es');
$TinyMCE->addLang('svenska','sv');
$TinyMCE->addLang('svenska-utf8','sv');
?>